account/urls.py
from django.conf.urls import url
from . import views
from django.conf import settings
from django.contrib.auth import views as auth_views


urlpatterns = [
    # url(r'^login/$', views.user_login, name="user_login"),        # 自定义登录
    url(r'^login/$', auth_views.login, name="user_login"),          # django内置方法登录
    url(r'^new_login/$', auth_views.login, {"template_name": "account/login.html"}),       # 传新的模板文件，需配置路径
    # url(r'^logout/$', auth_views.logout, name="user_logout"),  # 退出登录
    url(r'^logout/$', auth_views.logout,  {"template_name": "account/logout.html"}, name="user_logout"),  # 使用登录模板、退出登录
    url(r'^register/$', views.register, name="user_register"),  # 使用登录模板、退出登录
    url(r'^password-change/$', auth_views.password_change, {"post_change_redirect":"/account/password-change-done"}, name="password_change"),
    url(r'^password-change-done/$', auth_views.password_change_done, name="password_change_done"),
    url(r'^password-reset/$', auth_views.password_reset,{"template_name": "account/password_reset_form.html",
                                                         "email_template_name":"account/password_reset_email.html",
                                                         "subject_template_name":"account/password-reset-subject.txt",
                                                         "post_reset_redirect":"/account/password-reset-done"}, name="password_reset"),

    url(r'^password-reset-done/$', auth_views.password_reset_done, {"template_name":"account/password_reset_done.html"},
        name="password_reset_done"),
    url(r'^password-reset-confirm/(?P<uidb64>[-\w]+)/(?P<token>[-\w]+)/$', auth_views.password_reset_confirm,
        {"template_name":"account/password_reset_confirm.html",
         "post_reset_redirect":"/account/password-reset-complete"}, name="password_reset_confirm"),
    url(r"^password-reset-complete/$", auth_views.password_reset_complete, name="password_reset_complete"),


    url(r'^my-information/$', views.myself, name="my_information"),  # 配置个人信息页面的URL
    url(r'^edit-my-information/$', views.myself_edit, name="edit_my_information"),
    url(r'^my-image/$', views.my_image, name="my_image"),
]

blog/urls.py
from django.conf.urls import url
from . import views 

urlpatterns = [
    url(r'^$', views.blog_title, name='blog_title'),
    url(r'(?P<article_id>\d)/$', views.blog_article, name='blog_details'),
]

mysite/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include('blog.urls', namespace="blog", app_name='blog')),
    url(r'^account/', include('account.urls', namespace="account", app_name='account')),
    url(r'^article/', include('article.urls', namespace="article", app_name='article')),

]

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <!-- <meta http-equiv="X-UA-Compatible" content="IE=edge"> -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <!-- <link rel="stylesheet" href="http://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css"> -->
</head>
<body>
    {% include "header.html" %}
    <div class="container">
        {% block content %}{% endblock %}
    </div>
        {% include "footer.html" %}
        {% block javascript %}{% endblock %}
<!-- <script src="https://cdn.bootcss.com/jquery/3.2.1/jquery.js"></script>
<script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script> -->
</body>
</html>

templates/content.html
{% extends "base.html" %}

{% block title %}blog article{% endblock %}

{% block content %}
<div class="row text-center vertical-middle-sm">
    <h1>{{ article.title }}</h1>
</div>
<div class="row">
    <div class="row-xs-12 col-md-8">
        <p class="text-center"><span>{{ article.author.username }}</span><span style="margin-left:20px">{{ publish }}</span></p>
    </div>
<div>{{ article.body }}</div>
</div>
    <div class="col-xls-6 col-md-4">
        <h2>test_blog</h2>
        <p>django：www.testerhome.com</p>
        <img width="200px" src="{% static 'images/back.jpeg' %}">
    </div>
    {% endblock %}

templates/footer.html
<div class="container">
    <hr>
    <p class="text-centenr">copy right www.testerhome.com</p>
</div>

templates/header.html
{% load staticfiles %}
<div class="container">
    <nav class="navbar nacbar-default" role="navigation">
        <div class="navbar-header">
            <a class="nvbar-brand" href="https://www.testerhome.com">
                <img src="{% static 'images/back.jpeg' %}" width="100px">
            </a>
        </div>
        <div>
            <ul class="nav navbar-nav navbar-right" style="margin-right:10px">
                {% if user.is_authenticated %}
                <!--判断用户登录状态，已登录返回True 未登录走else语句-->
                <li>
                <div class="dropdown" style="margin-top:8px">
                    <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu"
                            data-toggle="dropdown">{{ user.username }}<span class="caret"></span></button>
                    <ul class="dropdown-menu">
                        <li><a href="{% url 'account:password_change' %}">修改密码</a></li>
                        <li><a href="{% url 'account:my_information' %}">个人信息</a></li>
                    </ul>
                </div>
                </li>
                <li><a href="#">{{ user.username }}</a></li>
                <li>
                    <a href="{% url 'account:user_logout'%}">Logout</a>
                </li>
                {% else %}
                <li>
                    <a href="{% url 'account:user_login'%}">LOGIN</a>
                </li>
                {% endif %}
            </ul>
            <!--<ul class="nav navbar-nav navbar-right">-->
                <!--<li>-->
                    <!--<a href="#">LOGIN</a>-->
                <!--</li>-->
            <!--</ul>-->
        </div>
    </nav>
</div>
<script src="{% static 'js/jquery.js' %}"></script>
<script src="{% static 'js/bootstrap.js' %}"></script>

templates/titles.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}blog titles{% endblock %}
{% block content %}
<div class="row text-center vertical-middle-sm">
    <h1>我的博客</h1>
</div>
<div class="row">
    <div class="col-xs-12 col-md-8">
    <ul>
    {% for blog in blogs %}
    <!-- <! #给博客标题添加超链接> -->
        <li><a href="{{ blog.id }}">{{ blog.title }}</a></li> 
    {% endfor %}
    </ul>
    </div>
    <div class="col-xs-6 col-md-4">
    <h2>look  me</h2>
    <p>my blog ：www.testerhome.com</p>
    <img width="200px" src="{% static 'images/back.jpeg' %}">
    </div>
</div>
{% endblock %}