account/urls.py
from django.conf.urls import url
from . import views
from django.conf import settings
from django.contrib.auth import views as auth_views


urlpatterns = [
    # url(r'^login/$', views.user_login, name="user_login"),        # 自定义登录
    url(r'^login/$', auth_views.login, name="user_login"),          # django内置方法登录
    url(r'^new_login/$', auth_views.login, {"template_name": "account/login.html"}),       # 传新的模板文件，需配置路径
    # url(r'^logout/$', auth_views.logout, name="user_logout"),  # 退出登录
    url(r'^logout/$', auth_views.logout,  {"template_name": "account/logout.html"}, name="user_logout"),  # 使用登录模板、退出登录
    url(r'^register/$', views.register, name="user_register"),  # 使用登录模板、退出登录
    url(r'^password-change/$', auth_views.password_change, {"post_change_redirect":"/account/password-change-done"}, name="password_change"),
    url(r'^password-change-done/$', auth_views.password_change_done, name="password_change_done"),
    url(r'^password-reset/$', auth_views.password_reset,{"template_name": "account/password_reset_form.html",
                                                         "email_template_name":"account/password_reset_email.html",
                                                         "subject_template_name":"account/password-reset-subject.txt",
                                                         "post_reset_redirect":"/account/password-reset-done"}, name="password_reset"),

    url(r'^password-reset-done/$', auth_views.password_reset_done, {"template_name":"account/password_reset_done.html"},
        name="password_reset_done"),
    url(r'^password-reset-confirm/(?P<uidb64>[-\w]+)/(?P<token>[-\w]+)/$', auth_views.password_reset_confirm,
        {"template_name":"account/password_reset_confirm.html",
         "post_reset_redirect":"/account/password-reset-complete"}, name="password_reset_confirm"),
    url(r"^password-reset-complete/$", auth_views.password_reset_complete, name="password_reset_complete"),


    url(r'^my-information/$', views.myself, name="my_information"),  # 配置个人信息页面的URL
    url(r'^edit-my-information/$', views.myself_edit, name="edit_my_information"),
    url(r'^my-image/$', views.my_image, name="my_image"),
]

article/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^article-column/$', views.article_column, name="article_column"),
]

blog/urls.py
from django.conf.urls import url
from . import views 

urlpatterns = [
    url(r'^$', views.blog_title, name='blog_title'),
    url(r'(?P<article_id>\d)/$', views.blog_article, name='blog_details'),
]

mysite/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include('blog.urls', namespace="blog", app_name='blog')),
    url(r'^account/', include('account.urls', namespace="account", app_name='account')),
    url(r'^article/', include('article.urls', namespace="article", app_name='article')),

]

article/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class ArticleColumn(models.Model):
    user = models.ForeignKey(User, related_name='article_column')
    column = models.CharField(max_length=200)
    created = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.column


'''
模型之间的关系为三种：  1、一对一  OneToOneField
                    2、一对多  ForeignKey
                    3、多对多  ManyToManyField
'''

article/forms.py
from django import forms
from .models import ArticleColumn

class ArticleColumnForm(forms.ModelForm):
    class Meta:
        model = ArticleColumn
        fields = ("column",)

article/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from .models import ArticleColumn
from django.views.decorators.csrf import csrf_exempt
from .forms import ArticleColumnForm
from django.http import HttpResponse


@csrf_exempt
@login_required(login_url='/account/login/')
def article_column(request):
    if request.method == 'GET':
        columns = ArticleColumn.objects.filter(user=request.user)
        column_form = ArticleColumnForm()
        return render(request, "article/article_column.html", {"columns":columns,"column_form":column_form})
    if request.method == "POST":
        column_name = request.POST['column']
        columns = ArticleColumn.objects.filter(user_id=request.user.id, column=column_name)
        print(columns)
        if columns:
            return HttpResponse("2")
        else:
            ArticleColumn.objects.create(user=request.user, column=column_name)
            return HttpResponse('1')

templates/article/article_column.html
{% extends "article/base.html" %}
{% load staticfiles %}
{% block title %}article column{% endblock %}
{% block content %}
<div>
    <p class="text-right"><button id="add_column" onclick="add_column()" class="btn btn-primary">add column</button> </p>
    <table class="table table-hover">
        <tr>
            <td>序号</td>
            <td>栏目名称</td>
            <td>操作</td>
        </tr>
        {% for column in columns %}
        <tr>
            <td>{{ forloop.counter }}</td>
            <td>{{ column.column }}</td>
            <td>--</td>
        </tr>
        {% empty %}
        <p>还没有设置栏目，太懒了</p>
        {% endfor %}
    </table>
</div>
<script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>
<script type="text/javascript" src="{% static 'js/layer.js' %}"></script>
<script type="text/javascript">
    function add_column(){
        var index =layer.open({
            type:1,
            skin:"layui-layer-rim",
            area:["400px", "200px"],
            title:"新增栏目",
            content:'<div class="text-center" style="margin-top:20px"><p>请输入新的栏目名称</p><p>{{column_form.column}}</p></div>',
            btn:['确定','取消'],
            yes:function(index, layero){
                column_name = $('#id_column').val();
                $.ajax({
                    url:'{% url "article:article_column" %}',
                    type:'POST',
                    data:{'column':column_name},
                    success:function(e){
                        if(e=='1'){
                            parent.location.reload();
                            layer.msg("good");
                        }else{
                            layer.msg("此栏目已有，请更换名称")
                        }
                    },
                });
            },
            btn2:function(index, layero){
                layer.close(index);
            }
        });
    }
</script>
{% endblock %}

templates/article/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <!-- <link rel="stylesheet" href="http://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css"> -->
</head>
<body>
<div class="container">
    {% include "article/header.html" %}
    <div class="col-md-2">
    {% include 'article/leftslider.html' %}
    </div>
    <div class="col-md-10">
    {% block content %}
    {% endblock %}
    </div>
    {% include 'article/footer.html' %}
</div>
        <!--{% include "footer.html" %}-->
        <!--{% block javascript %}{% endblock %}-->
<!-- <script src="https://cdn.bootcss.com/jquery/3.2.1/jquery.js"></script>
<script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script> -->
</body>
</html>

templates/article/footer.html
<div class="container">
    <hr>
    <p class="text-center">copy right www.testerhome.com</p>
</div>

templates/article/header.html
{% load staticfiles %}
<div class="container">
    <nav class="navbar navbar-default" role="navigation">
        <div class="navbar-header">
            <a class="navbar-brand" href="http://testerhome.com"><img width="100px" src="{% static 'images/backlogo.png' %}"</a>
        </div>
        <div>
            <ul class="nav navbar-nav" role="tablist">
                <li><a href="{% url 'article:article_column' %}">文章管理</a></li>
                <li><a href="{% url 'article:article_column' %}">后台管理</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right" style="margin-right:10px">
                <li><a href="{% url 'blog:blog_title'%}">网站首页</a></li>
                <li><span>{{ user.username }}</span></li>
                <li><a href="{% url 'account:user_logout' %}">Logout</a></li>
            </ul>
        </div>
    </nav>
</div>

templates/article/leftslider.html
<div class="bg-info">
    <div class="text-center" style="margin-top:50px;">
        <p><a href="{% url 'article:article_column' %}">栏目管理</a></p>
    </div>
</div>